import Head from 'next/head';
import Banner from '../components/home/Banner';
import Achievement from '../components/shared/Achievement';


export default function Home() {
  return (
    <>
      <Head>
        <title>Real Estate | Home</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Banner/>
      <Achievement/>
      
    </>
  )
}
